# Generated by Django 5.0.6 on 2024-07-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'complete')},
        ),
    ]
